//
// Created by Admin on 12/04/2023.
//

#ifndef OPENGL_GENERATIONTERRAIN_GENERATION_HPP
#define OPENGL_GENERATIONTERRAIN_GENERATION_HPP


class Generation {

};


#endif //OPENGL_GENERATIONTERRAIN_GENERATION_HPP
